trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
    - feature/*
    - bugfix/*
  paths:
    exclude:
    - src/test/postman

variables:
  apiName: 'whispir-sapi'
  version: '1.0.0-SNAPSHOT'

resources:
  repositories:
  - repository: azure-devops
    type: git
    name: azure-devops
    ref: refs/heads/main
extends:
  template: azure-pipelines-main.yml@azure-devops
  parameters:
    apiAssetId: 'whispir-system-api'
    apiAssetVersion: 'v1'
    featureCloudhubApplicationName: $(apiName)-ftr
    devCloudhubApplicationName: $(apiName)-dev
    sitCloudhubApplicationName: $(apiName)-sit
    uatCloudhubApplicationName: $(apiName)-uat
    prdCloudhubApplicationName: $(apiName)